resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: pull-request
    type: pull-request
    check_every: 1m
    icon: github-circle
    source:
      repository: UF-ACE/ace-home
      access_token: ((github.access-token))
      base_branch: master

jobs:
  - name: eslint
    plan:
      - get: pull-request
        trigger: true
        version: every
      - put: pull-request
        params:
          path: pull-request
          status: pending
      - task: lint
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: node, tag: "13"}
          inputs:
            - name: pull-request
          run:
            path: /bin/sh
            args:
              - -xec
              - |
                cd pull-request
                yarn install
                yarn eslint "components/**" "pages/**"
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure
      - put: pull-request
        params:
          path: pull-request
          status: success
